#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <executable file>"; exit
fi

name=$1
if [ ! -f $name ]; then
  echo "error: file '$1' does not exist"; exit
fi

./$name loop &
pid=$!

trap '' INT

echo "Monitoring memory usage of process $name:"
while true; do
  output=$(grep VmSize /proc/$pid/status)
  echo "$output - press ENTER to stop"
  read -t 2 && break
done

kill $pid
